### ISSUE TITLE
Cannot successfully run `docker compose up` 

### ISSUE THREAD

**Issue by lmsasu** [timeplus-io/proton#776] opened 2024-06-19 20:04 UTC
Hi all, 
I downloaded the docker-compose.yml. When I run `docker compose up` in its directory, I get:
```[+] Running 2/2
 ✔ proton Pulled                                                                                                                                                                                      46.1s 
 ✔ grafana Pulled                                                                                                                                                                                      4.4s 
[+] Running 2/0
 ✔ Container sensor_logger-proton-1  Created                                                                                                                                                           0.0s 
 ✔ Container sensor_logger-proxy-1   Created                                                                                                                                                           0.0s 
Attaching to grafana-1, proton-1, proxy-1
proton-1   | Processing configuration file '/etc/proton-server/config.yaml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/data-paths.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/docker_related_config.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/logger.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/openssl.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/user-directories.xml'.
proton-1   | Env variable is not set: TELEMETRY_ENABLED
proton-1   | Logging information to /var/log/proton-server/proton-server.log
proton-1   | Logging errors to /var/log/proton-server/proton-server.err.log
proton-1   | Env variable is not set: TELEMETRY_ENABLED
proxy-1    | Searching 'src':
proxy-1    | + Entry: 'index.routes.ts'
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container sensor_logger-proton-1 is unhealthy
```
This happens in Ubuntu 22.04, docker engine v 26.1.1.
What should I do?

Lucian

**Comment by yokofly** [comment] 2024-06-20 03:42
```
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container sensor_logger-proton-1 is unhealthy
```
can u share the health check section?

**Comment by lmsasu** [comment] 2024-06-20 08:15
> ```
> Gracefully stopping... (press Ctrl+C again to force)
> dependency failed to start: container sensor_logger-proton-1 is unhealthy
> ```
> 
> can u share the health check section?

Hi @yokofly, thanks for reply How do i see the health check section?

**Comment by yokofly** [comment] 2024-06-20 08:34
> > ```
> > Gracefully stopping... (press Ctrl+C again to force)
> > dependency failed to start: container sensor_logger-proton-1 is unhealthy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can u share the health check section?
> 
> Hi @yokofly, thanks for reply How do i see the health check section?

Hi, @lmsasu 
sorry, I misunderstood the issue, the docker-compose is here https://github.com/timeplus-io/proton/blob/develop/examples/awesome-sensor-logger/docker-compose.yml
, and I am working on reproduce it.

**Comment by yokofly** [comment] 2024-06-20 08:40
what i mean the health check is the https://github.com/timeplus-io/proton/blob/7fd74f9e6ceb304d807a84ded8a02b631dd57e7d/examples/awesome-sensor-logger/docker-compose.yml#L11-L17
usually in docker or k8s helm chart based we will use health check to make sure the dependent service is health.

for example:
grafana(function: monitor and visual) is rely on proton, if proton fail, the grafana shall not be started.
the previous log states unhealthy then it failed to start.

anyway, i am try to reproduce

**Comment by yokofly** [comment] 2024-06-20 09:20
Hi Lucian,

I was able to reproduce the issue, which seems to be a regression. because the old version is published in 5months ago.
Even after removing the healthcheck section from the yaml, the issue persists because `timeplus/sensor-logger-proxy` exits quickly.

Would you like to try other examples, or is this specific example crucial for your work? 
I'm currently tied up with other tasks and might not be able to address this in the next two days.

Thanks!

**Comment by jovezhong** [comment] 2024-06-20 10:22
Assigning this to @gangtao  since this related to how the init SQL is executed and how the healthcheck works. Gang refined this recently.

**Comment by yokofly** [comment] 2024-06-20 11:01
@gangtao  for a more stable  way, I recommend  to pin the image version instead use latest.

**Comment by lmsasu** [comment] 2024-06-20 12:24
> Hi Lucian,
> 
> I was able to reproduce the issue, which seems to be a regression. because the old version is published in 5months ago. Even after removing the healthcheck section from the yaml, the issue persists because `timeplus/sensor-logger-proxy` exits quickly.
> 
> Would you like to try other examples, or is this specific example crucial for your work? I'm currently tied up with other tasks and might not be able to address this in the next two days.
> 
> Thanks!

Hi @yokofly ,
Any working (older) version that functions is fine for me. I need it for now for a PoC. 
Lucian

**Closed as completed** 2024-06-21 05:51 UTC
Labels: question

**Comment by yokofly** [comment] 2024-06-21 07:11
hi @lmsasu 
plz take try old version below or use the latest code
`image: ghcr.io/timeplus-io/proton:latest` => `image: ghcr.io/timeplus-io/proton:1.5.8-rc`

**Comment by lmsasu** [comment] 2024-06-22 15:39
Hi @yokofly ,
Still no luck:
```
Attaching to grafana-1, proton-1, proxy-1
proton-1   | Processing configuration file '/etc/proton-server/config.yaml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/data-paths.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/logger.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/openssl.xml'.
proton-1   | Merging configuration file '/etc/proton-server/config.d/user-directories.xml'.
proton-1   | Env variable is not set: TELEMETRY_ENABLED
proton-1   | Logging information to /var/log/proton-server/proton-server.log
proton-1   | Logging errors to /var/log/proton-server/proton-server.err.log
proxy-1    | Searching 'src':
proxy-1    | + Entry: 'index.routes.ts'
proton-1   | Env variable is not set: TELEMETRY_ENABLED
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container sensor_logger-proton-1 is unhealthy

```

Lucian

**Comment by yokofly** [comment] 2024-06-23 08:24
Hi, @lmsasu 
can u tell me the platform (x86 or arm or other chip?), system(linux ubuntu2204? or macOS or windows 10?)
I recall the old version only first work in macOS arm chip.
