### ISSUE TITLE
Cannot run `describe external table ch_local`

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#554] opened 2024-02-04 03:48 UTC
**Describe what's wrong**

In Proton 1.4.2, after I created an external table for ClickHouse, I want to verify the connection and show columns.
Naturally I ran `describe external table ch_local` but it failed.

The full list of what are working and what are not
❌ describe external table ch_local
❌ describe table ch_local
✅ describe ch_local
✅ describe stream ch_local
❌ describe external stream ch_local

It's surprising and confusing `describe stream ch_local` works. `describe ch_local` could be okay, but we should also allow `describe external table ch_local`

**Comment by zliang-min** [comment] 2024-02-04 05:50
Not a bug, it's by design. Just use `DESCRIBE ch_local` , no need to add extra words for describing an external table. Only `DROP EXTERNAL TABLE` is implemented, and that's because `drop` is a destructive action, we want to provide a way to precisely expression the intention ( like, I want to drop a external table, not any stream ). `DESCRIBE` does not have such issue.

Closing the issue. Feel free to reopen the issue if you still think `DESCRIBE EXTERNAL TABLE` should be implemented.

`describe stream ch_local` might feel confusing, but `stream` in this context is more like a general word ( it's like `table` in ClickHouse ), and external table, external stream, etc are all streams ( or tables ) but using different engines. That means, you can actually create an external table using `CREATE STREAM` like this:

```sql
CREATE STREAM my_ex_table ENGINE = ExternalTable SETTINGS type='clickhouse',address='localhost:9000',table='my_table';
```

**Closed as not planned by zliang-min** 2024-02-04 05:50 UTC
Labels: bug
